language: objective-c
xcode_project: PersonnummerExample/PersonnummerExample.xcodeproj # path to your xcodeproj folder
xcode_scheme: PersonnummerExample
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)